#![cfg(all(feature = "mbedtls_adapter", feature = "rustls_adapter", feature = "rsa"))]

// ECDSA is excluded from byte-for-byte CSR comparison as ECDSA provider
// uses randomized signing.

use ftx_cert_build::rustls_adapter::RustlsCryptoProvider;
use ftx_cert_build::{crypto_provider::DefaultPkParameters, name_builder::DnType, Csr, NameBuilder};
use mbedtls::{hash, pk::Pk};
use pkix::types::{RsaPkcs15, Sha256};
use rustls_pki_types::PrivateKeyDer;

type Rsa = RsaPkcs15<Sha256>;

fn build_csrs() -> (Csr, Csr, Pk) {
    let algorithm = RsaPkcs15(Sha256);
    let _ = rustls::crypto::aws_lc_rs::default_provider().install_default();
    // Generate once and import the same key
    let mut rustls_key: PrivateKeyDer<'static> = Rsa::generate_pk(&mut RustlsCryptoProvider::new()).unwrap();
    let mut mbedtls_key = Pk::from_private_key(rustls_key.secret_der(), None).unwrap();

    let subject = NameBuilder::new().add_dn(DnType::CommonName, "csr.example").build_subject();
    let mbedtls_csr = Csr::mbedtls_crypto_builder()
        .with_subject(subject.clone())
        .with_self_signing_key(&mut mbedtls_key, algorithm.clone())
        .unwrap()
        .build_csr()
        .unwrap();
    let rustls_csr = Csr::rustls_crypto_builder()
        .with_subject(subject)
        .with_self_signing_key(&mut rustls_key, algorithm)
        .unwrap()
        .build_csr()
        .unwrap();

    (mbedtls_csr, rustls_csr, mbedtls_key)
}

fn parts(csr: &Csr) -> (Vec<u8>, Vec<u8>, Vec<u8>) {
    pkix::yasna::parse_der(csr, |reader| {
        reader.read_sequence(|reader| {
            let info = reader.next().read_der()?;
            let algorithm = reader.next().read_der()?;
            let signature = reader.next().read_bitvec()?.to_bytes();
            Ok((info, algorithm, signature))
        })
    })
    .unwrap()
}

fn compare_and_verify(mbedtls: &Csr, rustls: &Csr, key: &mut Pk) {
    let (mbedtls_info, mbedtls_algorithm, _) = parts(mbedtls);
    let (rustls_info, rustls_algorithm, _) = parts(rustls);
    assert_eq!(mbedtls_info, rustls_info, "CSR request info are not identical");
    assert_eq!(mbedtls_algorithm, rustls_algorithm, "signature algorithms are not identical");

    // Verify signatures generated by mbedtls & rustls providers.
    for csr in [mbedtls, rustls] {
        let (info, _, signature) = parts(csr);
        let mut digest = [0; 32];
        hash::Md::hash(hash::Type::Sha256, &info, &mut digest).unwrap();
        key.verify(hash::Type::Sha256, &digest, &signature).unwrap();
        // Change the digest to cause failure
        digest[0] ^= 1;
        assert!(key.verify(hash::Type::Sha256, &digest, &signature).is_err());
    }
}

#[test]
fn rsa_csrs_are_identical() {
    let (mbedtls, rustls, mut key) = build_csrs();
    compare_and_verify(&mbedtls, &rustls, &mut key);
    assert_eq!(mbedtls, rustls, "RSA CSRs are not identical");
}
