name: Fortanix Cert Builder CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88
        with:
          targets: x86_64-unknown-linux-gnu
          toolchain: stable
          components: rustfmt, clippy
      - name: Run Sanity checks
        run: |
          ./sanity-check.sh